name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to the project directory on your server
            cd /var/www/fastapi-app/fastapi-book-project

            # Pull the latest changes from the main branch
            git pull origin main

            # Activate the virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the systemd service to pick up the changes
            sudo systemctl restart fastapi.service

            #Check the status of the service
            sudo systemctl status fastapi.service
